//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artist
    {
        public long artist_id { get; set; }
        public string artist_description_th { get; set; }
        public string artist_description_en { get; set; }
        public string artist_type { get; set; }
        public int artist_view { get; set; }
        public string artist_picture { get; set; }
        public string ArtistPicture_L_Lo { get; set; }
        public string ArtistPicture_L_Hi { get; set; }
        public string ArtistPicture_S_Lo { get; set; }
        public string ArtistPicture_S_Hi { get; set; }
        public int artist_publisherforartistId { get; set; }
    }
}
