//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactus
    {
        public int contactUs_id { get; set; }
        public System.DateTime contactUs_datetime { get; set; }
        public string contactUs_name { get; set; }
        public string contactUs_email { get; set; }
        public string contactUs_phone { get; set; }
        public string contactUs_message { get; set; }
    }
}
