//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class csv
    {
        public Nullable<long> id { get; set; }
        public string Title___TH { get; set; }
        public string Title___EN { get; set; }
        public string Photo { get; set; }
        public string Artist___TH { get; set; }
        public string Artist___EN { get; set; }
        public string Length { get; set; }
        public string Lyrics { get; set; }
        public string Album___TH { get; set; }
        public string Album___EN { get; set; }
        public string Released_date { get; set; }
        public string C_Views__today__30_days__total_ { get; set; }
        public string Language { get; set; }
        public string Genres { get; set; }
        public string Publisher { get; set; }
        public string Status { get; set; }
        public string Price { get; set; }
        public string Copyright { get; set; }
        public string Track_Number { get; set; }
        public string URL_iOS { get; set; }
        public string URL_Android_Other { get; set; }
        public string URL_RTMP { get; set; }
        public long csv_id { get; set; }
    }
}
