//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceinfo
    {
        public long deviceInfo_id { get; set; }
        public string deviceInfo_deviceID { get; set; }
        public string deviceInfo_model { get; set; }
        public string deviceInfo_deviceToken { get; set; }
    }
}
