//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myrecord
    {
        public long myrecord_id { get; set; }
        public long user_id { get; set; }
        public long song_id { get; set; }
        public string myrecord_description { get; set; }
        public System.DateTime myrecord_datetime { get; set; }
        public string myrecord_length { get; set; }
        public string myrecord_uploadURL { get; set; }
    
        public virtual user user { get; set; }
        public virtual song song { get; set; }
    }
}
