//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlist
    {
        public playlist()
        {
            this.playlisttosong = new HashSet<playlisttosong>();
        }
    
        public long playlist_id { get; set; }
        public long user_id { get; set; }
        public string playlist_description { get; set; }
        public System.DateTime playlist_createdDatetime { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<playlisttosong> playlisttosong { get; set; }
    }
}
