//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlist
    {
        public int playlist_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string playlist_description { get; set; }
        public Nullable<System.DateTime> playlist_createdDatetime { get; set; }
    }
}
