//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publisherforartist
    {
        public publisherforartist()
        {
            this.artist = new HashSet<artist>();
        }
    
        public long publisherforartist_Id { get; set; }
        public string publisherforartist_description { get; set; }
    
        public virtual ICollection<artist> artist { get; set; }
    }
}
