//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class singinghistory
    {
        public int singinghistory_id { get; set; }
        public int user_id { get; set; }
        public int song_id { get; set; }
        public int artist_id { get; set; }
        public System.DateTime singinghistory_date { get; set; }
    }
}
