//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public int song_id { get; set; }
        public string song_originName { get; set; }
        public string song_engName { get; set; }
        public int song_genre { get; set; }
        public int song_languageId { get; set; }
        public int song_albumId { get; set; }
        public int song_artistId { get; set; }
        public string song_length { get; set; }
        public string song_keywords { get; set; }
        public string song_lyrics { get; set; }
        public int publisherforsong_id { get; set; }
        public System.DateTime song_releasedDate { get; set; }
        public string song_URL_picture { get; set; }
        public int song_status { get; set; }
        public System.DateTime song_addedDate { get; set; }
        public Nullable<decimal> song_price { get; set; }
        public int song_view { get; set; }
        public string song_URL_iOS { get; set; }
        public string song_URL_Android_Other { get; set; }
        public string song_URL_RTMP { get; set; }
        public string song_Copyright { get; set; }
        public Nullable<int> song_Track_Number { get; set; }
        public string song_streamURLWithVocal { get; set; }
        public string song_streamURLWithoutVocal { get; set; }
    }
}
