//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.myrecord = new HashSet<myrecord>();
            this.playlist = new HashSet<playlist>();
            this.singinghistory = new HashSet<singinghistory>();
            this.songrequest = new HashSet<songrequest>();
            this.viewhistory = new HashSet<viewhistory>();
            this.wtbtokens = new HashSet<wtbtokens>();
        }
    
        public long user_id { get; set; }
        public sbyte user_status { get; set; }
        public int usergroup_id { get; set; }
        public int user_type { get; set; }
        public string user_fbUserId { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> user_createdDatetime { get; set; }
        public Nullable<System.DateTime> user_modifiedDatetime { get; set; }
        public Nullable<System.DateTime> user_lastlogin { get; set; }
        public string user_avartar { get; set; }
        public string user_token { get; set; }
        public string user_retoken { get; set; }
        public string APNS_token { get; set; }
    
        public virtual ICollection<myrecord> myrecord { get; set; }
        public virtual ICollection<playlist> playlist { get; set; }
        public virtual ICollection<singinghistory> singinghistory { get; set; }
        public virtual ICollection<songrequest> songrequest { get; set; }
        public virtual ICollection<viewhistory> viewhistory { get; set; }
        public virtual ICollection<wtbtokens> wtbtokens { get; set; }
    }
}
