//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public sbyte user_status { get; set; }
        public int usergroup_id { get; set; }
        public int user_type { get; set; }
        public int user_fbUserId { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> user_createdDatetime { get; set; }
        public Nullable<System.DateTime> user_modifiedDatetime { get; set; }
        public Nullable<System.DateTime> user_lastlogin { get; set; }
        public string user_avartar { get; set; }
        public string user_token { get; set; }
        public string user_retoken { get; set; }
        public string APNS_token { get; set; }
    }
}
