//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingSpaze.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewhistory
    {
        public long ViewHistory_Id { get; set; }
        public long User_Id { get; set; }
        public long Song_Id { get; set; }
        public System.DateTime ViewHistory_Date { get; set; }
    
        public virtual song song { get; set; }
        public virtual user user { get; set; }
    }
}
